### ISSUE TITLE
Flag dialog text is not readable in deeporange-indigo theme [🐛]

### ISSUE THREAD

**Issue by RezaRahmati** [juice-shop/juice-shop#1069]
# :bug: Bug report

## Description
The flag dialog text is black and is not readable in deeporange-indigo theme

A clear and concise description of the problem...

### Is this a regression?

Yes, the previous version in which this bug was not present was: `x.y.z`

## :fire: Exception or Error

![image](https://user-images.githubusercontent.com/10086092/58680103-55a62280-8334-11e9-9570-efbcf62bfc06.png)

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
@MarcRler, could you take a look at this please and tweak the color settings of the `deeporange-indigo` theme a bit? Or did you maybe do that already over in the `facelift` branch?

**Comment by MarcRler** [comment]
![alternative](https://user-images.githubusercontent.com/18336861/58768154-f3992780-8596-11e9-860e-2aa9cb5d5997.png)
------------------------------------------------------------------------------------------------------
I've adapted the theming in the Indigo area so that it is suitable for black text (see picture).

**Comment by bkimminich** [comment]
@MarcRler that looks great! Could you send a PR for just the theming changes into `develop` then I'll make it part of the 8.7.0 release end of this week. Thanks!

**Comment by bkimminich** [comment]
Fixed with #1077. To be released this Friday with `v8.7.0`.
