### ISSUE TITLE
HTML Injection

### ISSUE THREAD

**Issue by Soluspero** [juice-shop/juice-shop#1156]
Hello, I am a beginner/novice, learning penetration testing from few days ago. I'm just curious to know about HTML injection vulnerability which I found while solving XSS  challenge in star-3 category. 
The test case to produce  HTML injection as follows:-
OWASP Juice shop 7.4.1

1) Submit the register user data with the following data:-
{"email":"img@img.com<img src=\"/public/images/JuiceShop_Logo.png\"> ","password":"img123","passwordRepeat":"img123"}
2) Login with any user
3) Go to administration page, then you will see the newly registered user with image.

I just want to confirm, Is this HTML injection or XSS vulnerability?
I'll be glad, if you response.

**Comment by bkimminich** [comment]
Hi! In a nutshell, XSS is just a worse-case scenario of HTML Injection. There might be scenarios where you can inject HTML but scripts are successfully sanitized or prevented by input validation, but it's almost always possible to beat those with sophisticated XSS payloads. I guess that's why XSS has become kind of synonymous for HTML Injection these days.

**Comment by Soluspero** [comment]
Ok, Thanks.
