### ISSUE TITLE
XSS Tier 1.5 screw up User Profile

### ISSUE THREAD

**Issue by PiAil** [juice-shop/juice-shop#1185]
A simple payload ```<script>``` screw up the **User Profile** interface. I guess this is not a bug, and that it is the way XSS work, it can screw up things, but as I'm not sure, I prefer leave a ticket here.

**Comment by bkimminich** [comment]
There's no way to have an XSS vulnerability but only allow "harmless XSS", so that's just how it is. If you break the profile for your user, you can always use another user or simply restart the server to wipe the application back into vanilla state. Your challenge hacking progress will be preserved in a cookie by default.
