### ISSUE TITLE
docker container don't need to save

### ISSUE THREAD

**Issue by happyliubei** [juice-shop/juice-shop#1226]
I am doing the challenges of juiceshop by running it on docker. Once I have stopped my container by mistake and next time when I create a new container, the progress of finished challenges is still there.

Does that mean I don't need to save container when doing the challenge? And is the progress data saved in my browser side so next time it can restore automatically?

**Comment by bkimminich** [comment]
Exactly, the progress is saved in a 🍪. If you don't delete those and don't change URL or ports it will be restored on restart. But anything you created in DB will be gone, like users or feedback etc.

**Comment by yeroc-sebrof** [comment]
Hey, I've run into an issue where the cookie didn't restore my progress. I has a look at the solution to solving challenge 999 but if I'm spinning up the lab for a bunch of students I don't want to spoil this challenge for them if more of them encounter this issue.

The lab restarted three times total so I'm worried that the continue code maybe reset itself on the penultimate restart? I can't backtrace the issue but here is the content of the continue code currently:
`Kq37B4Dk8naMjQ1R95mLbwdvEhkTgfqyUgosxpA6PlEYZOoyVrgpzeXNxWv2`

I'm still able to use `docker log juice-shop` to see if they've complete the challenge but their score-board is clearly not showing the challenges complete.

**Comment by yeroc-sebrof** [comment]
Would it be reasonable to also submit a feature request to make the database reset functions optional due to this issue?

**Comment by bkimminich** [comment]
@yeroc-sebrof I do not understand what the Challenge 999 has to do with what you encounter. Also, the continue code does never reset as long as you don't delete the 🍪 yourself or by using an incognito browser.

Every student is using their own Juice Shop instance or are they all bashing on one? Of course then the first continueCode to trigger after any server restart wins and sets the DB for all. Which is why only one student per instance is the official recommendation.

**Comment by bkimminich** [comment]
@yeroc-sebrof No, this is a core feature of the Juice Shop that it is unbreakable as it always starts in vanilla state, no matter what crazy XSS you persisted with SQLi etc. There's no difference if it runs in Docker or not except that you would provision a new container, but that would also have a vanilla state DB.

**Comment by yeroc-sebrof** [comment]
@bkimminich the reference to Challenge 999 was because I've been looking at reversing the cookie to check what's happened. I have also been looking at restoring progress based on the Docker Logs and crafting these challenge complete requests to ensure progress pulled across.

**Comment by yeroc-sebrof** [comment]
I understand that refreshing the database on start is key functionality but due to a student's progress being lost I hoped this step could be skipped with a flag on docker run just like the `NODE_ENV=unsafe` flag. Then due to juice shop running in a container if the student managed to completely break their instance a new container could be spun up and we could use the cookie restore point or have the back up of pulling completed challenges from the original containers logs.

**Comment by bkimminich** [comment]
This would conceptually break the data creator and all reset tasks running on start-up (like deleting order PDFs, restoring overwritten files etc.) - it's not just the database.
