### ISSUE TITLE
[⭐] Challenge idea : RCE/Reverse shell through captcha submit

### ISSUE THREAD

**Issue by Scar26** [juice-shop/juice-shop#1346]
# :star: Challenge idea

### Description

 Juice Shop has a manually implemented captcha system, wherein an arithmetic question is generated through randomized strings and then eval is called on that string to generate the answer. This challenge can be implemented two ways:

1. Captcha statements are now generated on the client side, and then sent to endpoint which only returns a Captcha Id

2. Add a hidden, unused parameter that takes a captcha statement, evals the answer, updates it in the database and then returns the captchaId. This, according to me, would be more believable as it's basically based on a deprecated debug variable accidentally left in a manually implemented system.

I would love some feedback on which path to take

The final aim of the challenge could be to read a particular file, as we already have two DoS challenges as of now.

### Underlying vulnerability/ies

 I guess this could fall under security misconfiguration 

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|      :heavy_check_mark:       | :star::star::star:                   |

### Possible attack flow

The attacker notices that captcha is generated when a request is made to the `rest/captcha` endpoint and a json response is returned which contains the statement under the name `captcha`. They fuzz around a bit and notice that by sending a url parameter of the same name, they can manipulate the json response. This prompts the question, how was the `answer` computed? The most obvious way would be eval. The attacker tries some preliminary code injection and it works. And Viola! the challenge is solved

**Comment by bkimminich** [comment]
We already have two types of CAPTCHA challenges (on the _Data Export_ and _Customer Feedback_ screens) and also two challenges where `eval` is involved, so I wouldn't really go for another one to be honest. What is your opinion on that, @J12934 / @wurstbrot?

**Comment by Scar26** [comment]
@bkimminich @J12934 any thoughts on this one?
Should I leave it for now?

**Comment by J12934** [comment]
I like the general challenge idea. Its pretty plausible that a developer would use eval to calculate such a arithmetic riddle.

But I also agree with Björn that already have two similar challenges around RCE, so it's probably not worth it to add another one.

What what be a real addition would be to have an example on how to set up a proper reverse shell using one of the existing RCE challenges similar to the shaker logger demo. Might be hard to to because the rce are somewhat protected from actually doing real harm.

**Comment by Scar26** [comment]
Ok I'll try to think of something to modify the existing challenges

**Comment by bkimminich** [comment]
Please don't meddle with the existing CAPTCHA challenge to make it into an RCE. If you want to take up @J12934's idea of building an exploit demo for getting a web shell via Juice Shop, feel free to do that, because that'd be really cool. It would need to bypass the sandboxing we did to make the challenges less easy to shoot yourself in the foot with... :-D ... You should look at all challenges, which are disabled on Heroku/Docker, because those are the ones considered "suitable" for this kind of exploit. If you can make a remote shell work with any other challenge, please contact me privately, because then we have to fix an actually overlooked security risk... 😀

**Comment by Scar26** [comment]
Alright, thanks
