### ISSUE TITLE
All solved challenges automatically vanished after some hours on heroku[🐛] 

### ISSUE THREAD

**Issue by Xeek3y** [juice-shop/juice-shop#1395]
Hey, i really like this lab and i deployed this lab on herokuapp as well as on my local machine and i solved till rating 3 vulnerability[all of them1+2+3] on the firefox browser and next day when i reopened the site on chrome browser then everything vanished then i thought it's maybe my fault i may have clicked on **Delete All history** button that appears when we open the webpage...
**or** maybe i opened the heroku deployed app[juice-shop site] on another browser so it didn't recognize my cookie or whatever reason. 
So i solved the lab again and not visited the site for some hours but it was still open and the site was running on my firefox browser so when i refreshed the webpage again then the same thing happened again.. everything vanished again, i have to start again from beginning :(
Please fix this issue!
Thanks!

**Comment by bkimminich** [comment]
The `continueCode` cookie will save your progress. It must somehow fail to get created or get deleted unintentionally. Please check what's happening to your cookie. Maybe paste its value into a text file for safe keeping and then see what's happening.

**Comment by bkimminich** [comment]
Your first case when you switched browsers is expected in combination with Heroku, as they occasionally put apps to sleep and wake them up on demand, which is essentially a restart. So your Chrome could obviously not access your Firefox's cookies to restore. When you use Firefox all the time, as your second case implies, this should not happen, unless you're in ingognito mode or use some plugin that would prevent cookies on the site.

TL;DR: Please make sure nothing is interfering with cookies in your Firefox.

**Comment by bkimminich** [comment]
Also, if somone else uses the same Heroku instance with you, whoever visits it first after a server restart, will restore their solved challenges from their continue code.

**Comment by Xeek3y** [comment]
Hello thanks for giving me solution but i tried everything that you said but none worked for me:
Some points i wanna mention before i tested this:

1) Does someone else operate my pc? The Answer is no, no one uses my pc other than me!
2) Did i logged in or opened the site on another browser as well like chrome? No i didn't. i only used firefox!
3) I copied the previous cookie and everything from **continueCode** to **io** token and imported again but none worked for me, i was observing this behaviour from 2 days that's why i didn't replied!

But no it's not working and also i faced this issue before on my local juice-shop lab too and it got the same issue that's why i opened this issue thread as bug on the first sight, because i was familiar with this situation before!

I guess it's a session management and token expiration bug or something else, please fix this on upcoming version or in this version.
Thanks!

**Comment by Xeek3y** [comment]
> Also, if somone else uses the same Heroku instance with you, whoever visits it first after a server restart, will restore their solved challenges from their continue code.

Any update?

**Comment by bkimminich** [comment]
> I guess it's a session management and token expiration bug or something else, please fix this on upcoming version or in this version.

I on the other hand am quite confident it's **not** a Juice Shop issue, because I haven't heard _anybody else_ report this issue ever before. Unfortunately I cannot reproduce your problem, neither locally nor on any of my Heroku instances. Can you try the following _exact_ steps and confirm the behavior please?

1. Close _all browsers_ on your PC
1. Start Juice Shop locally with `npm start`
2. Open Firefox in a _Privacy Mode_ (to make sure none of your plugins etc. interfere)
3. Visit http://localhost:3000/#/score-board (this should solve the _Score Board_ challenge)
4. Confirm if the `continueCode` cookie is set for `http://localhost:3000`
5. Close the green challenge notification
6. Go to http://localhost:3000/#/search
7. Kill the Juice Shop server and start is again with `npm start` (leave the browser window open while doing so)
8. You should get the server restart notification and the _Score Board_ solved notification again:
![image](https://user-images.githubusercontent.com/3531020/82899950-110b9200-9f5c-11ea-8543-537237123f6f.png)

**Comment by bkimminich** [comment]
> Does someone else operate my pc? The Answer is no, no one uses my pc other than me!

PS: I wasn't talking about someone operating your PC, I was talking about someone else using your publicly accessible Heroku instance. If I know your Heroku URL, and I visit it before you do after an instance restart, _my challenge progress_ will be restored. When you visit the instance 5sec later your visit will not trigger another restore, because the server remembers to only do it once after a restart. (Which is why I like to refer to Juice Shop as a "single-player application"...)

But all this is probably unrelated if you have the cookie restore issues also on a locally hosted instance.

**Comment by Xeek3y** [comment]
> > I guess it's a session management and token expiration bug or something else, please fix this on upcoming version or in this version.
> 
> I on the other hand am quite confident it's **not** a Juice Shop issue, because I haven't heard _anybody else_ report this issue ever before. Unfortunately I cannot reproduce your problem, neither locally nor on any of my Heroku instances. Can you try the following _exact_ steps and confirm the behavior please?
> 
> 1. Close _all browsers_ on your PC
> 2. Start Juice Shop locally with `npm start`
> 3. Open Firefox in a _Privacy Mode_ (to make sure none of your plugins etc. interfere)
> 4. Visit http://localhost:3000/#/score-board (this should solve the _Score Board_ challenge)
> 5. Confirm if the `continueCode` cookie is set for `http://localhost:3000`
> 6. Close the green challenge notification
> 7. Go to http://localhost:3000/#/search
> 8. Kill the Juice Shop server and start is again with `npm start` (leave the browser window open while doing so)
> 9. You should get the server restart notification and the _Score Board_ solved notification again:
>    ![image](https://user-images.githubusercontent.com/3531020/82899950-110b9200-9f5c-11ea-8543-537237123f6f.png)

Alright will update here i'm currently testing and will do whatever you said above, btw thanks..



> > Does someone else operate my pc? The Answer is no, no one uses my pc other than me!
> 
> PS: I wasn't talking about someone operating your PC, I was talking about someone else using your publicly accessible Heroku instance. If I know your Heroku URL, and I visit it before you do after an instance restart, _my challenge progress_ will be restored. When you visit the instance 5sec later your visit will not trigger another restore, because the server remembers to only do it once after a restart. (Which is why I like to refer to Juice Shop as a "single-player application"...)
> 
> But all this is probably unrelated if you have the cookie restore issues also on a locally hosted instance.

And no, i didn't gave anyone my herokuapp url, i'm the only one who operates all this.
But i'm not sure if someone is doing subdomains enumeration/scanning/bruteforcing on herokuapp domains and maybe that's why it is happening with me but it's less likely so yeah i'm the only who solves that!
