### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by kairosart** [juice-shop/juice-shop#1580]
I'm trying to install Juice Shop on Kali Linux 2020. According to https://github.com/mukkul007/sqli-labs-kali2 instructions.

Node.js v14.15.4
Npm:
{
  'juice-shop': '12.5.0',
  npm: '6.14.10',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.4',
  openssl: '1.1.1i',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}
k

When I run "npm install" the following process starts and never ends up.

![image](https://user-images.githubusercontent.com/6544570/106735872-0ccc6400-6615-11eb-9109-f9d427c99b88.png)

**Comment by bkimminich** [comment]
That can't be a Juice Shop specific issue, I suppose. Can you get more details out of the log maybe to see where it's stuck exactly?

**Comment by bkimminich** [comment]
Please check https://pwning.owasp-juice.shop/appendix/troubleshooting.html for solutions to your issue and also check if that tool or third party instructions you use have a problem or mistake or are just outdated etc. Thanks.

**Comment by bkimminich** [comment]
I'm closing this issue as support questions are suppsed to be raised on https://gitter.im/bkimminich/juice-shop anyway and due to lack of information. If the troubleshooting hints don't help you, please make sure any 3rd party instructions you use from https://github.com/mukkul007/sqli-labs-kali2 are actually up to date and if all that fails, please get in touch via Gitter. Thanks!
