### ISSUE TITLE
[🐛] A possible bug when solving the challenge "Expired Coupon"

### ISSUE THREAD

**Issue by TracingDrone** [juice-shop/juice-shop#1582]
# :bug: Bug report

## Description

Hello! I`ve found a bug when solving the "Expired Coupon" in another way.

I found a way to bypass the date validation by using breakpoint and editing the "this.clientdate" in the console.

The discount worked, but the challenge didn`t solved.

### Is this a regression?

IDK...

## :microscope: Minimal Reproduction

I use the Juice Shop in Simplified Chinese, but I think these pictures would contain necessary infomation.

![1](https://user-images.githubusercontent.com/31869612/107479543-39a0ee00-6bb6-11eb-9fdc-6c157d435429.png)
![2](https://user-images.githubusercontent.com/31869612/107479551-3c034800-6bb6-11eb-85d9-e0050993124b.png)
![3](https://user-images.githubusercontent.com/31869612/107479553-3d347500-6bb6-11eb-92c6-410ae29b4186.png)
![4](https://user-images.githubusercontent.com/31869612/107479557-3e65a200-6bb6-11eb-9b69-65e6d3407ff2.png)
![5](https://user-images.githubusercontent.com/31869612/107479558-3efe3880-6bb6-11eb-8e78-098774651ae5.png)

## :fire: Exception or Error

No.

## :deciduous_tree: Your Environment

Docker

### Additional Information

Windows10, Firefox85.0.2, OWASP ZAP

**Comment by bkimminich** [comment]
I just checked, the epoch time value you have in the screenshot is equivalent to `Fri Mar 08 2019 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)` which is exactly the `validOn` of the `WMNSDY2019` coupon, so it was rightfully accepted. So far, so good.

Now, the only place where things could then go wrong with the challenge check is this line:

```
utils.solveIf(challenges.manipulateClockChallenge, () => { return campaign.validOn < new Date() })
```

This is a nice beginner-friendly bug, I think, because it's probably not so hard to trace and reproduce. So, I'll leave it open for a while for e.g. future GSoC student candidates or other new contributors.

**Comment by chinggg** [comment]
I am new beginner and have interests in GSoC. I also use the Juice Shop in Simplifed Chinese. I will have a try.

**Comment by chinggg** [comment]
I have reproduced the bug successfully. ~~But I did not solve the challenge even if I adjust the time of my machine manually, which is the expected solution.~~ The green text has shown up saying I will have 75% discount. But that is not enough. It requires me to accomplish the payment to finish the task. 
```javascript
    if (campaign && couponDate == campaign.validOn) { // eslint-disable-line eqeqeq
      utils.solveIf(challenges.manipulateClockChallenge, () => { return campaign.validOn < new Date() })
      return campaign.discount
    }
```
~~But it seems that the line that checks whether the problem is solved is within the if statement and have nothing to do about the payment.~~
And I am still wondering what is wrong with this line. Initially I suspect that `campaign.validOn` is equal to `new Date('Mar 08, 2019 00:00:00 GMT+0100').getTime()`, and could not be compared with the object new Date(). But I found the usage correct by making some small tests. And the solution to edit the "this.clientDate" seems to be definitely correct, even more correct than the official solution? `campaign.validOn < new Date()` will definitely be true because the Date object is truly the time right now and is larger than any date in 2019. Or maybe I misunderstood something due to ignorance of JavaScript or the Juice Shop project. I cannot figure it out.
Now it is nearly 1 a.m in my timezone so I have to go sleep. I will go back and give it another try when I wake up.

**Comment by chinggg** [comment]
@TokinoLynx 请问可以确认一下订单最后实际付款后真的打折了吗?我试验发现仅仅在图中那行断点后修改clientDate值,虽然UI中显示成功获得折扣,但SessionStorage里的clientDate仍然是当前时间,所以我最后付款时仍然没有折扣,所以此项任务未完成.
而如果我再修改一下Session Storage里的时间,任务就通过了.

**Comment by chinggg** [comment]
![image](https://user-images.githubusercontent.com/24590067/107599815-c7371900-6c5c-11eb-8011-a296626cb63c.png)
That may be another bug(or not a bug at all)? `this.clientDate` has been assigned successfully to `1551999600000`.(I also checked it in Firefox Debugger-Watch expressions). But the `couponDetails` in the Session Storage still uses the current time.
That is in conflict with this line which obviously use the value of `this.clientDate`. I cannot figure it out now.
```javascript
sessionStorage.setItem('couponDetails', `${ this.campaignCoupon }-${ this.clientDate }`);
```
If I modify the `couponDetails` in the Session Storage manually then finish the payment, the challenge "Expired Coupon" will be solved. So I think the line below which checks if the challenge is solved is correct. The problem may lie somewhere else(or no problem at all).

> Now, the only place where things could then go wrong with the challenge check is this line 
> ```
> utils.solveIf(challenges.manipulateClockChallenge, () => { return campaign.validOn < new Date() })
> ```

**Comment by TracingDrone** [comment]
> 
> 
> @TokinoLynx 请问可以确认一下订单最后实际付款后真的打折了吗?我试验发现仅仅在图中那行断点后修改clientDate值,虽然UI中显示成功获得折扣,但SessionStorage里的clientDate仍然是当前时间,所以我最后付款时仍然没有折扣,所以此项任务未完成.
> 而如果我再修改一下Storage里的时间,任务就通过了.

我今天早上测试了一下。也许你说对了，如果只修改`this.ClientDate`的话，接下来确认订单会显示折扣，但下单成功的页面则是原价。

I tested this morning. Maybe you're right, if I modify  `this.ClientDate` only, the discount show up normally in the order confirmation page, but the discount don't apply after I submit the order.

如果修改系统时间的话，下单后才会显示正常的折扣。

The discount apply successfully only if I change the system time.

我还没测试`sessionStorage`的修改。如果修改完Session Storage才能完成任务的话，那应该不是Bug，而是我不够细心。

I haven't test the modification of `sessionStorage`, if the challenge can be solved by editing  `sessionStorage`,  it would prove that my careless lead to the"bug".

@chinggg

**Comment by bkimminich** [comment]
Ah ok, if the coupon wasn't really accepted, then it makes sense you didn't see the confirmation. In our step by step solution we recommend to change the system time, and our end to end test https://www.github.com/bkimminich/juice-shop/tree/master/test%2Fe2e%2FbasketSpec.js overloads the `new Date()` call to give back the campaign date.
