### ISSUE TITLE
[🐛] Basket Access challenge solved by switching between two users

### ISSUE THREAD

**Issue by rixtrayker** [juice-shop/juice-shop#1632]
View another user basket challenge solved itself after logging with another user on the same browser..
( After changing between users multiple times ) I think that was cause of cookies

**Comment by bkimminich** [comment]
To reproduce this behavior, could you tell us what users you used and if the behavior is reproducable after a specific number of switches or occurs rather "randomly"? Also, are you using a single tab or multiple ones? The session handling is terrible by design, but it shouldn't hit the challenge too easily, so every bit of information would help. Thanks!

**Comment by bkimminich** [comment]
I can't reproduce the behavior you describe when doing the following loop 5 times:

1. Log in as `demo`
2. View basket
3. Log out
4. Log in as `admin@juice-sh.op` 
5. View basket
6. Log out
7. Repeat step 1

So I would assume you have done _something_ else in the meantime as well, but without knowing what it is, I can't determine if that is a bug or not.

**Comment by rixtrayker** [comment]
May be I had another tabs logged in with another user, then refreshed basket in one of those tabs. It sent api the action via socket and found that the basket wasn't mine.
That is what I guessed.
I'll reproduce it and inform you soon.
