### ISSUE TITLE
[🐛] Issue with UserProfile.js as it says 500 TypeError: Cannot read property 'dataValues' of null

### ISSUE THREAD

**Issue by faisalbasha1982** [juice-shop/juice-shop#1643]
# :bug: Bug report

## Description

I have installed the owaspjuiceshop app on heroku and tried to access it firefox esr in the Kali Linux OS. After 
registeration and login to the portal, I clicked on accounts -> my email address , for accessing userProfile, I get
an error page. It does not take me to the user profile page.

### Is this a regression?

Yes, the previous version in which this bug was not present was: `x.y.z`

## :fire: Exception or Error

<pre><code>
OWASP Juice Shop (Express ^4.17.1)
500 TypeError: Cannot read property 'dataValues' of null
       at /app/build/routes/userProfile.js:24:41
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
 npm install
 npm start
</code></pre>

**Comment by bkimminich** [comment]
```
            const loggedInUser = security.authenticatedUsers.get(req.cookies.token);
            if (loggedInUser) {
                models.User.findByPk(loggedInUser.data.id).then(user => {
                    let template = buf.toString();
                    let username = user.dataValues.username;
```

Hi @faisalbasha1982! The code above is where this error occurs. It seems you have a recognized token, but when your user is looked up in the database it cannot be found. And then the subsequent access to its properties fails. I could imagine, that your app was restarted on Heroku after you logged in. This might go unnoticed easily if you just browse products etc. Then when accessing your profile the user did no longer exist in the DB, as all data is wiped upon restart.

I am pretty sure you will not have this problem when you register, log in and immediately open the profile. I just tried that on Heroku and it worked.

As this whole bad session management behavior is intentional and part of some hacking challenges, I cannot really "fix" this issue. Also if we do a null check, that would look like the developers thought about the possibility of this happening - which is out of character for the imaginary Juice Shop developers, so I'll just keep it as it is.

Please let me know if this problem keeps reoccuring no matter how fast you do Register>Login>Profile on Heroku or elsewhere.
