### ISSUE TITLE
[⭐] Embed an Github action challenge

### ISSUE THREAD

**Issue by commjoen** [juice-shop/juice-shop#1688]
# :star: Challenge idea: Embed Github action in a challenge

### Description
This challenge nicely ties in with the discussion at https://github.com/juice-shop/juice-shop/pull/1687 as discussed earlier.
Given that a lot of mistakes are made with github actions, workflows and secrets, it would be cool to actually base a challenge on it. There are 3 things we could play with:

- insecure github action as part of the juice-shop organization. This plugin basically holds a "secret" which we can extract to solve a problem for the dockerized releases for instance
- insecure secrets management: have an open repo where everybdoy can "contrinbute" in order to extract secrets of it, which are part of another challenge (perhaps less doable)

### Underlying vulnerability/ies
- Poorly configured pipeline components
- Poorly configured CI/CD pipeline

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :grey_question:      | :star:                               |
|     :heavy_check_mark: / :x:      | :star::star:                         |
|     :grey_question:      | :star::star::star:                   |
|     :grey_question:      | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

- check the code of the insecure plugin
- check the secret by creating a branch at the repo with an openssl base64 encoding applied twice.

**Comment by bkimminich** [comment]
> insecure secrets management: have an open repo where everybdoy can "contrinbute" in order to extract secrets of it, which are part of another challenge (perhaps less doable)

Could we come up with something where a fork of the juice-shop main repo is able to trigger something in a verification-only repo because we "forgot" to forbid some (harmless) workflow on PRs? The Juice Shop could then solve the challenge by either checking for a certain generated hash in the "User Feedback" form or offers a URL (revealed by the verification repo) where you pass the GitHub fork and/or some secret that is GH user specific?

Sounds a bit convoluted, but might be similar to how we check the SSRF/SSTi challenges today...
