### ISSUE TITLE
[🚀] Implement code corrections or infrastructure assets for fix security vulnerabilities for learning purposes

### ISSUE THREAD

**Issue by tarciziovn** [juice-shop/juice-shop#1722]
# :rocket: Feature request
### Description

For those who would like to learn not only how to explore the vulnerabilities but the ways how to fix them, would be great if developers could learn how to implement countermeasures to fix juice-shop webapp vulnerabilities.

### Solution ideas

Considering that security vulnerabilities could be fixed in several ways, such as code fixes, config files fixes, or by using infrastructure components such as Web Application Firewall, API Gateway, or even the use of security libraries solutions. All countermeasures could be implemented as branches from the master version where developers could merge their local copy of the master version with the branch of each countermeasure implementation for each vulnerability.
Infrastructure solutions that require the deployment of other system processes such as IPTables or pfSense could be implemented as changes on docker-compose file for including those assets with their configurations or even when the changes imply some code fix that includes any new library dependency. Obviously, we know that if there are any security issues that imply in code fixes or configuration fixes, they should be fixed as fast as possible, but when the security team finds some vulnerability, they need to do remediation until the development team fixes the code. In other cases, security assets act as a second layer of protection (principle of Defense in Depth) e.g. input filters that block any pattern that contains SQL Injection or XSS. For this reason, would be great to show both ways of corrections. 

All instructions addressing vulnerabilities and how to fix them with the respective git commands or branches references to do all git merges from branch fixes over the master version could be documented on new sections at https://pwning.owasp-juice.shop, or in a new web page e.g. [https://**fixing**.owasp-juice.shop](https://fixing.owasp-juice.shop)., having them all cross references.

I also suggest to create a new version of the system backend in other programming languages (at least in PHP and Java) only for the learning purposes of how to fix the vulnerabilities discussed on this issue, but I will open a new issue only for discussing this.

**Comment by bkimminich** [comment]
Minus the [new version of system backend-part](https://github.com/juice-shop/juice-shop/issues/1723) I like this idea, but it would face some very tough obstacles.

The Juice Shop was _designed_ to be hacked, not fixed. It contains lots of code for challenge verification you wouldn't want to have in any code-fix exercise. For this reason we decided in this year's Google Summer of Code project, to implement the new [Coding Challenges](https://pwning.owasp-juice.shop/part1/challenges.html#coding-challenges) the way we did: Letting users spot a vuln in the code and then let them select a possible fix from some predefined options, rather than letting them edit and fix the code. The latter was considered, but dropped due to the effort for _verifying_ all possible ways to fix a code vuln minus the "no-brainer" fixes like just removing the entire functionality etc.etc. Also I wouldn't want to have such a code fix exercise become a big RCE vuln in the project either. In https://pwning.owasp-juice.shop/appendix/code-snippets.html I described all the steps needed to create and maintain (!) a coding challenge in Juice Shop. It is already quite a lot to keep track of.

I like the general idea of your PR-/branch-based code fixing exercises and using CI/CD to then verify sound possible (but hard, see above) as well. I would just not try to attach something like this to Juice Shop or any other non-lesson-based vuln app. This sounds more like an entirely new project, or something that could well fit into the scopes of projects that already use a lesson-based or single-exercise flow.
