### ISSUE TITLE
[🚀] Backend code reimplementing for educational purposes

### ISSUE THREAD

**Issue by tarciziovn** [juice-shop/juice-shop#1723]
# :rocket: Feature request

### Description

Create a new version of the system backend in other programming languages for the educational purpose of learning how to fix system vulnerabilities, as discussed in [this issue](https://github.com/juice-shop/juice-shop/issues/1722).

### Solution ideas

I suggest to create separate projects for reimplementing the backend written in NodeJS for the following languages (in priority order): 
- Java
- PHP
- Python
- Ruby on Rails

I suggest as frameworks used in implementations for Java, PHP, and Python, respectively: Spring, Laravel, and Django, but it is only a started idea open to discussions.

If it's also convenient redo the front-end in ReactJS and Vue.JS for exploring how to fix security issues in those view frameworks  /libraries I also suggest start discussions about this topic.

### Possible alternatives

About the use of frameworks suggested in last item, I suggest as alternative path the implementation of backend using for Java pure JAX-RS libraries, pure PHP and for Python the use of Flask.

For the frontend I also suggest as alternative path the implementation in pure HTML + CSS + JavaScript (jQuery)

**Comment by bkimminich** [comment]
Re-creating the Juice Shop backend or frontend in any other tech stack as the given one will never happen within the scope of this project, as this can inevitably only hurt it in one of two ways:

1. Either the alternate backends/frontends will end up as a _half-hearted attempt to replicate_ the thousands of work hours put into the project, thus delivering a worse quality than the original, thus damaging the Juice Shop "brand". Nothing I'd ever support as part of the project, seen that happen in spin-offs of the frontend and also a translation of the docs. Both never were finished or even close to getting anywhere.
2. In order to achieve an actually acceptable quality, so much effort needs to be put into the alt backends/frontends, that _it would overwhelm any single Open Source developer_ probably already during implementation but latest during maintenance where the variants would have to play "catch up" with the original version. If they wouldn't, they're back in situation 1. described above. Also, nothing I'd put into the official project, not as a branch, not as its own repo under the GitHub org.

Of course anyone can still try to go for it on their own, and if (!) there is a sensisble outcome, I'm more than happy to list it on https://owasp.org/www-project-juice-shop/#div-ecosystem under _Endorsed Open Source Projects_ until the day that it stops being maintained or becomes otherwise incompatible etc.

I would still not encourage to do this, especially because there are **so many** vulnerable apps in the languages you listed, see https://owasp.org/www-project-vulnerable-web-applications-directory.
