### ISSUE TITLE
[🚀] Add a "back" button to the tutorial pop-ups

### ISSUE THREAD

**Issue by CrazyKidJack** [juice-shop/juice-shop#1785]
# :rocket: Feature request

### Description

 A clear and concise description of the problem or missing capability...
When going through challenge tutorials, the "pages" will often trigger/change on accident or early than desired. There is no way to go back which means that if you miss something, you only option is to completely start the tutorial over.

### Solution ideas

 If you have a solution in mind, please describe it.
Add a "back" button to the tutorial pop-ups

### Possible alternatives

 Have you considered any alternative solutions or workarounds?
The only one I'm aware of is starting the tutorial completely over

**Comment by bkimminich** [comment]
The tutorials are progressing based on certain condition checks, e.g. a text field having some value or a button being clicked. Other steps are progress after a fixed number of seconds, and some of those can be "skipped" by clicking on the speech bubble. Others can't be skipped to avoid exactly those accidental overlooking of hints. But the step hints which are really important are mostly unskippable.

I'm not in favor of letting the user "fiddle" with the state of the tutorial progress even more, because that is likely to cause more issues than anything.

A restart of a tutorial is quite simple by just refreshing the Browser window and going back to the Score Board.

**Comment by CrazyKidJack** [comment]
I think it is the "fixed number of seconds" ones that I have the most trouble with. But also, since the click-skipping is possible... sometimes I accidentally click twice. In those cases, it would be awful nice to be able to click back

**Comment by bkimminich** [comment]
These two changes address the issue of missing hints without implementing a "back" button (which would have messed with the tutorial state engine, see https://github.com/juice-shop/juice-shop/issues/1785#issuecomment-1079452857)

![image](https://user-images.githubusercontent.com/3531020/162705276-53561074-c3b4-40c2-a11c-0537a780967b.png)
