### ISSUE TITLE
[🚀] OWASP Top 10 2021 Migration

### ISSUE THREAD

**Issue by avishayil** [juice-shop/juice-shop#1791]
# :rocket: Feature request

### Description

While testing some ideas for CTF I encountered this project. Great work!
Since we're trying to stay "up to date" with our standards and risk assessment, thought it would be a good idea to migrate the existing challenges to the "new" OWASP Top 10 2021 structure:
![OWASP Top 10 2017 -> 2021 Mapping](https://owasp.org/Top10/assets/mapping.png)

### Solution ideas

I think that it might be a good idea to open a project, to migrate all existing gaps to the new structure, then in a different project add new challenges gradually to cope with the missing items in 2021 Top 10:
- [A04:2021-Insecure Design](https://owasp.org/Top10/A04_2021-Insecure_Design/)
- [A08:2021-Software and Data Integrity Failures](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/)
- [A10:2021-Server-Side Request Forgery](https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/)

**Comment by bkimminich** [comment]
Juice Shop already has the entire Top Ten 2021 covered, including the three items you listed above. The reason why Juice Shop uses its own _Challenge Categories_ instead of just using the exact names of Top Ten entries is the instability of the latter over the years. What I did instead, is having a mapping table to OWASP Top Ten and also other resources from our categories: https://pwning.owasp-juice.shop/part1/categories.html#category-mappings - You will notice that no Top Ten 2021 entries are missing. For an overview of which challenges belong to which category, check the Score Board or take a look here: https://owasp.org/www-project-juice-shop/#div-challenges
