### ISSUE TITLE
[🚀] Add help for deploying to non-Heroku PaaS

### ISSUE THREAD

**Issue by dbartholomae** [juice-shop/juice-shop#1870]
# :rocket: Feature request

### Description

[Heroku is closing down their free tier](https://blog.heroku.com/next-chapter). It would be great to have another option for online deployment that is free to reduce setup times in workshop settings.
The solution should allow for deploying a version of Juice Shop with a browser only, without requiring any local setup.

### Solution ideas

E.g. fly.io offers a free tier. They don't have a deploy button like Heroku does, but it should be possible to add a manual GitHub workflow so that users can
1. Fork this repo
2. Set up a fly.io account
3. Save the fly.io API token into a secret in the forked repo 
4. Press the button to run the manual GitHub workflow

I'm willing to provide this as a PR.

### Possible alternatives

There might be other alternatives to fly.io that I'm not aware of (I just did a 5 minute search on that topic). Also, instead of setting up the GitHub workflow and configuration in this repo, it might work to write more detailed and longer instructions for setting up the project on fly.io

**Comment by bkimminich** [comment]
Please be aware that hosting an intentionally vulnerable application with even the intent to **hacking** it, might be against the terms of use of a hosting provider. From Heroku I have an actual confirmation from 2016 via support ticket that this is fine for our official instances and also user-hosted instances as long as no DDoS happens.

I won't recommend anything else for users where this is not given, especially in free-tier territory. The recently added Gitpod option for example is more fore contributors (which is why I might move it out of the README and into the eBook instead soon). Anyone using their own AWS/GCP/Azure account we simply expect to know what they're doing and what their contract allows. Heroku, as mentioned, was provably fine with Juice Shop instances being hosted and hacked.

For a Heroku replacement we'd need a similar statement from the hosting provider. Also I'd want to look into their history with OSS and also check their overall background a bit, because I won't do marketing for some startup that might just pull a "no more free tier"-stunt rather sooner than later.

TL;DR: Ideas for alternatives welcome, preferably easy ones of course. No PRs yet, please.

**Comment by dbartholomae** [comment]
Sounds good! Can I support on getting that information from fly.io? I'm not affiliated with them in any way, so this might actually be a bit harder for me as it would be for you, as I'm not representing this project either, but I'm happy to help any way I can :)

**Comment by bkimminich** [comment]
No rush, I'll check some alternatives and options and see what we'll recommend before Heroku takes their free tier offline in November.
