### ISSUE TITLE
Found a replacement for Heroku!

### ISSUE THREAD

**Issue by Milk-Cool** [juice-shop/juice-shop#1903]
Can't really find a fitting template for this, sorry.

Found a free replacement for Heroku: render.com. Maybe add instructions on deploying to render?

**Comment by bkimminich** [comment]
Render doesn't seem to offer a similar "Click button on README to deploy" approach as Heroku has, so I wouldn't consider it an actual replacement for the current _easiest way to get Juice Shop running_ Heroku currently offers.

For the Juice Shop official instances I might actually look into this, because so far I haven't heard back from the Salesforce OSS team. For regular Juice Shop instances Render is basically just another hosting option like GitPod or all the major cloud providers imho.
