### ISSUE TITLE
[🚀] Secure Code Review of Juice Shop

### ISSUE THREAD

**Issue by Josh-Beck** [juice-shop/juice-shop#2074]
# :rocket: Secure Code Markdown Commentary

### Description

Howdy! I am going to be presenting on secure code review at an upcoming conference. I will be walking through the Juice Shop repository to explain code review methodologies and show what vulnerabilities look like in code. With this, I wanted to create a resource that attendees could access outside of the presentation, with some of this information. I figured I could create a markdown file and include it in the Juice Shop repository, then link to it for the presentation. 

So my questions: Would y'all like a commentary written in markdown that explains secure code review using the Juice Shop? Is there already a location where walkthroughs and commentaries are stored within the repository (not in the references file)?

[Link to presentation abstract, search for "Juice Shop"](https://www.nationalcybersummit.com/Program/2023-Agenda)

Thanks!

**Comment by bkimminich** [comment]
Hi! Always good to hear someone is using Juice Shop as an example! 😅👍

If I understand your presentation scope correctly, this sounds more like something that would live outside the Juice Shop ecosystem, as it's much similar to a hacking video or challenge automation blog post etc. than to an internal resource on the Juice Shop repo itself.

We did introduce a new https://github.com/juice-shop/juice-shop-tutorials repo, but my idea for that was rather Juice Shop tutorials, not really tutorials for hacking or code analysis. Maybe, an additional chapter in the companion guide at https://pwning.owasp-juice.shop/ could be considered, but I personally am not keen of ending up with a maintenance burden for the code snippets in that chapter whenever we refactor something. So, TL;DR, maybe this is best put in its own place and just added to the REFERENCES.md.

On another note, I would highly recommend you take a look at the Code Snippet API endpoints (https://pwning.owasp-juice.shop/appendix/code-snippets.html#rest-endpoints) Juice Shop has already for its own coding challenges, rather than using the actual codebase. The snippets are already cleansed from all challenge validation logic, so they are much more realistic than going through the unfiltered code base.

**Comment by Josh-Beck** [comment]
Thanks for the quick feedback! I'll review the code-snippets section and link in the ref.md file. 😄
