### ISSUE TITLE
Add mutation testing for server-side tests

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#219]
### Questions / Challenges
1. probably requires a dedicated runner that can handle `jasmine-node` being run through `serverTests.js` in its own process?
2. execution time expected to be disastrous as for each run of `serverTests.js` _all_ tests will be executed which takes ~5-8sec including server start and database wipe. Any chance for @stryker-mutator to intervene?
3. Keeping the server run and just wipe the DB to solve 2. partially will probably not do it. I suppose some mutations will result in the server being crashed by the `frisby.js` API tests, which is fine as this will result in unexpected `500` errors, thus failing the overall suite run and killing that mutant. But to recover from that, a server restart per mutant seems like the only viable option.
### `serverTests.js`

```
'use strict'

var spawn = require('cross-spawn')
var colors = require('colors/safe')
var server = require('./../server.js')

server.start({ port: 3000 }, function () {
  var jasmineNode = spawn('jasmine-node', [ 'test/server', '--junitreport', '--output', 'build/reports/server_results' ])

  function logToConsole (data) {
    console.log(String(data))
  }

  jasmineNode.stdout.on('data', logToConsole)
  jasmineNode.stderr.on('data', logToConsole)

  jasmineNode.on('exit', function (exitCode) {
    console.log('Jasmine-Node exited with code ' + exitCode + ' (' + (exitCode === 0 ? colors.green('SUCCESS') : colors.red('FAILED')) + ')')
    server.close(exitCode)
  })
})
```

<hr>

:question:/CC @nicojs, @simondel
##

**Comment by nicojs** [comment]
Hi @bkimminich this is a cool use case :+1: 

As for the test runner: i added [issue #164](https://github.com/stryker-mutator/stryker/issues/164) for this. Also custom test runners are also supported, however its not well documented. For example, your custom test runner could just call your serverTests.js file (with some arguments). In https://github.com/stryker-mutator/stryker/issues/137 you can see an example and drawbacks.

### 1. Best case: independent stateless unit tests

Tests are stateless. Meaning that we can run tests in any order we want, the beforeEach and afterEach hooks should build and tear down the state needed for that single test. We should be able to run tests in parallel as well, so no global resource can be altered (i.e. a database).

### 2. Somewhat ok' ish case: independent stateful tests.

Tests are stateful in the sense that they cannot be run in parallel, because they use a global resource (i.e. database). However they are independent, meaning they can be run in any order you want, because the before and after hooks bring the global resource in the correct state.

### 3. Worst case: dependent stateful tests

Tests are stateful, like in 2, but are also order dependent. Meaning that they cannot be ran out of order. This is generally a bad design, you should be able to at least rewrite it to be case 2.

Stryker should be able to support all cases with degrading performance,  but for now: it only supports case 1 because it tries to run all tests in parallel always (not configurable). I added [issue #136](https://github.com/stryker-mutator/stryker/issues/163) for this.

**Comment by bkimminich** [comment]
Server unit tests already have Stryker configuration of their own.
