### ISSUE TITLE
Show vulnerability page/location/tipp in scoreboard

### ISSUE THREAD

**Issue by wurstbrot** [juice-shop/juice-shop#305]
As a student, new to security, I want to know the location of a vulnerability.
As an advanced security specialist I don't want to see the location of a vulnerability.

Therefore, an advanced score-board function and an newbie score-board function is need.
I prefere to have a button on the top of the score-board which is labled as "Newbie modus on" to turn on the effect of giving tipps on hover.

- Hover: "XSS Tier 1", Tipp: Can be found on http://localhost:3000/#/search
- Hover "Login Admin", Tipp can be found on http://localhost:3000/#/search
- Hover "Access a confidential document", Tipp can be found during the order process

I am open to discuss this in more detail during the App Sec EU.

**Comment by bkimminich** [comment]
So, basically every challenge gets a `hint` column, that is only shown as a tool tip in "newbie mode"? Nice idea!

The hint could also be used in the CTF extension, by adding a question there if hints should be created for CTFd.

I would suggest to also have a config property to allow the newbie button or not. For some CTFs you might not want to give this option at all. In that case the datacreator script should probably not even populate the `hint` column, otherwise people would just get the hints from the API directly.

**Comment by wurstbrot** [comment]
I thought to not send hints in case _newbie mode_ is off. But to not populate it in datacreator is even better.

**Comment by bkimminich** [comment]
Yes, I thought about simply just not exposing it in the API as well, but it would not be immune to `UNION SELECT` attacks against the `Challenges` table.

**Comment by bkimminich** [comment]
:warning: All in-app hints should be consistent with hints given in https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/.

**Comment by bkimminich** [comment]
* [x] Setting the hint as a `title` works but looks quite ugly. If it's supposed to be a tooltip, **it should at some point become a proper Bootstrap/CSS tooltip**.

It might also be worth discussing if showing a hint on mouse hover is the best idea. It might happen accidentally.

A possible alternative: **Using a dedicated `Show hint` button**.

* Each challenge could then also track if their hint was used
* This might then be used to provide some extra information in the %-score gauge how many challenges were solved w/ hints vs. w/o hints (maybe using a bicolored gauge?)
* On the other hand, this does not really say anything because, as mentioned earlier, hints could just have been harvested via API (or SQL injection)

**Comment by wurstbrot** [comment]
We can place the hints into a separate sqllite-db which is not accessible via SQL-Injection.

In https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/ is the page for the challenges not given. During my modules I don't have enough time to let the students search for the page. A link to the page (if possible, as "Access a confidential document"  shouldn't link directly).
We could also have two hint types. A "Newbie Mode" with descriptions and a "Really Newbie Mode" with descriptions and the page link.

**Comment by bkimminich** [comment]
Actually the light bulbs are the links to each hint, e.g. https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/score-board.html#find-the-carefully-hidden-score-board-page.

It would be an option to avoid redundancy to just have the "Hint" (or "Unsolved") button link to the corresponding section in the ebook...

**Comment by bkimminich** [comment]
I personally wouldn't distinguish between normal newbies and noobish newbies... Some users might take that assessment personal... 🤔

**Comment by bkimminich** [comment]
Just saw the distinct SQLite DB idea. I thought about having the challenges themselves in a separate one when I started the project, but dropped it for not really being worth the hassle (and need for *real security*) that comes with it.

If someone really wants to cheat, let them.

**Comment by bkimminich** [comment]
Released with 3.1.0
