### ISSUE TITLE
Different behavior of Login with Google

### ISSUE THREAD

**Issue by thefishermanhacker** [juice-shop/juice-shop#310]
I'm not sure if its a bug or that's how it should behave, but if you access to locahost:3000 you'll see Google sign in button, but if you try with ip ip:3000 then it won't be available to user.
Scenario:
1. Run juice-shop with docker.
2. Open Chrome and explorer to ip:3000/#login and you won't see the Google login button.
3. Open Chrome and explorer to localhost:3000/#login and you'll see the Google login button.

**Comment by bkimminich** [comment]
That's just how OAuth works: I needed to register valid auth domains at Google, and only those will provide OAuth login. I hide the button for unrecognized URLs, that's why on generic `localhost` it works. Same for all Heroku instances (although right now it only works for HTTPS there) and some other staticly defined domains.

There's no way to "fix" this, as it's basically a security feature of the OAuth mechanism.
