### ISSUE TITLE
CTF deployment help.

### ISSUE THREAD

**Issue by battletux** [juice-shop/juice-shop#547]
I'm looking to host, larger, juices-hop CTF later in the year and need so advice on how best to do this.

Last year it was a small scale ctf of only 7 instances, so I ran 7 docker containers and gave each participant their own instance and port number. However this year I am expecting it to be a larger deployment (albeit no idea on numbers yet) and I am not sure how to best do this.

From looking in the juice-shop book, it mentions about FBCTF being used to host a juice-shop ctf that spun up instances on demand for the teams, is there any detailed documentation on how this was done? I'm not familiar with FBCTF at present and my docker skills are not enough to get the on-demand unique instances for each team.

Ideally I'd want to run the juice-shop stuff along with other CTF's from places like Vuln hub to give a good range of challenges.

**Comment by bkimminich** [comment]
@J12934, can you give a few ideas to @battletux on how you did your CTF setup at your company?

**Comment by J12934** [comment]
Hi 👋
We have run CTF Games with about 40 Juice Shop instances so far, in which every team gets their own instance. 

To do this we are using a self developed service which we call "Juice Balancer" this service is basically a loadbalancer which ensures that every team can only access their own Juice Shop instance. This is currently still a internal closed source project, but we are planning to release this as an Open Source project in the near future, so that everybody can host it this way. I cannot give an exact ETA but I'm planning to release it before / during the Open Security Summit.

We are also using FBCTF which works similarly to CTFd but has a more involved visual representation of a CTF Game. But FBCTF isnt directly needed for JuiceBalancer it is "just another CTF Gameboard"

**Comment by battletux** [comment]
Morning, Thanks for the reply. I'll look forward to seeing the release in June of your tool @J12934 

Do you have any pointers on ways to implement this sort of on-demand spinning up of containers? Talking to a colleague about it he seems to think Origin/Openshift might me a way to go.

**Comment by J12934** [comment]
No unfortunately not really, we have thought about it but we haven't really needed it.
Its pretty easy to just spin up a few more containers up then needed and let them idle. The don't really consume to many resources when not actually in use.

We have used Rancher in previous iteration to orchestrate the containers and to scale the number of Juice Shop instances. If we have noticed that we needed more containers we could just increase the number of instances in Rancher. Worked really smoothly.
