### ISSUE TITLE
Submit forms by hitting enter

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#753]
With the new frontend it is no longer possible to submit forms (like the login, search form) by hitting enter.
This is pretty annoying if you are used to it 😕

**Comment by bkimminich** [comment]
Yes, that is totally annoying, agreed! I stumble over this in every demo as well... :angry:

**Comment by aaryan01** [comment]
Hi! I have successfully fixed this issue for main login form, I'd like to submit a PR for that and then work on search and other areas.

**Comment by bkimminich** [comment]
Awesome! 👍 Yes, please submit a PR then I'll check it works on my Browser as well!

**Comment by bkimminich** [comment]
@aaryan01, I think we need to make the submit by `Enter` conditional, as it currently also works when the _Log In_-button is disabled because the form is incomplete.

**Comment by aaryan01** [comment]
@bkimminich I have submitted a PR which solves this issue for many forms. Still working on the search form.

**Comment by bkimminich** [comment]
:bug: The _Contact Us_ form can currently be submitted with zero stars when hitting Enter
:bug: The _Request Recycling Box_ form can currently be submitted with a Deliver Address shorter than 20 characters

I assume there might be similar issues in other forms as well due to the attempted replication of the form validity conditions? Isn't it possible to retrieve the enabled/disabled state of the button inside the Angular components and allow or deny submitting via Enter that way?
