### ISSUE TITLE
Unintentional Forged Feedback

### ISSUE THREAD

**Issue by navyspeed** [juice-shop/juice-shop#822]
I had completed the Forged Feedback unintentionally.  

The issue comes from logging into an account and then logging out.  Even after being logged out of the account if you access the contact us customer feedback tab that account will still show up as the author.  I am utilizing the herokuapp and chrome.

**Comment by bkimminich** [comment]
Thanks for reporting this! I'll leave it open for a bit as we're running out of _good first issue_ tickets faster than usual at the moment thanks to many new contributors! 🙌

**Comment by AbdelrhmanMagdy** [comment]
@bkimminich  I started to work on this issue and i have a question .. the problem here is that the token in cookies didn't be deleted when logout function fired so the user service still can fetch the user info and that's happened on the version deployed on heroku only. I tried the same behavior locally, when i logout the token removed from the cookie so it's works well .. have you any idea why the deployed version behavior differ from the develop version ? i see that develop has the same logging out logic as master branch

**Comment by alejandrosaenz117** [comment]
@AbdelrhmanMagdy  We could possibly solve this with the `ngOnDestroy` life cycle hook to ensure the token is removed after logout and when the component is destroyed.

**Comment by bkimminich** [comment]
Cross-fixed by solution to #535.

**Comment by bkimminich** [comment]
Fixed with 31d8e38654ee028fce923e84df4459e4a9553000.
