### ISSUE TITLE
Sequelize 5.x migration

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#933]
Juice Shop should at some point be migrated to the latest Sequelize 5.x version which requires the following issues to be addressed in the process. One of the following approaches would have to be chosen:

1. Make `epilogue` _(which seems unmaintained on GitHub by now)_ work with Sequelize 5.x
2. Switch to different API mapping library _(needs follow-up change to one typosquatting challenge)_
3. Create all API endpoints manually _(probably least favorable due to effort)_

Also the application needs to be checked for the use of string-based operators and those would have to be replaced with `Op.`-operators. Damage to any challenges needs to be checked as well.

**Comment by J12934** [comment]
😅 The "Database to REST Api" packages don't seem to survive for too long. Didn't we switch to `epilogue` because some other library was unmaintained?

Did look through the sequelize issues and somebody suggested to use [finale-rest](https://www.npmjs.com/package/finale-rest#migrate-from-epilogue). This also has a `epilogue` compatibility mode.

**Comment by bkimminich** [comment]
> This project aims to be a Sequelize 4.x and 5.x compatible version of Epilogue.

I :heart: it! Will try it our with current Sequelize and then see if we survive 4:arrow_right:5 migration with it... Thanks!
